runtime: nodejs12

handlers:
  - url: /static/js/(.*)
    static_files: build/static/js/\1
    upload: build/static/js/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /static/css/(.*)
    static_files: build/static/css/\1
    upload: build/static/css/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /static/media/(.*)
    static_files: build/static/media/\1
    upload: build/static/media/(.*)
    secure: always
    redirect_http_response_code: 301
  - url: /(.*\.(json|ico))$
    static_files: build/\1
    upload: build/.*\.(json|ico)$
    secure: always
    redirect_http_response_code: 301
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301